name: "PagerDuty On-call"
description: "Find out who's on call next for a given schedule"
inputs:
  token:
    description: "PagerDuty API token"
    required: true
  schedule-id:
    description: "Schedule ID of on-call schedule to look up"
    required: false
  escalation-policy-id:
    description: "Escalation policy ID of on-call schedule to look up"
    required: false
  start-date:
    description: "Start date of on-call to query (in ISO8601)"
    required: false
  end-date:
    description: "End date of on-call to query (in ISO8601)"
    required: false
outputs:
  person:
    description: "Name of person on call at escalation level 1"
  userId:
    description: "PagerDuty user ID of person on call at escalation level 1"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "bell"
  color: "purple"
